# <center>Heart Attack Predictor</center>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
dt = pd.read_csv("heart_attack_china_Classified.csv")
dt

Age  Blood_Pressure  CVD_Risk_Score  Gender  Smoking_Status  \
0        55             104              78       1               0   
1        66             142              49       0               1   
2        69             176              31       0               1   
3        45             178              23       0               1   
4        39             146              79       0               1   
...     ...             ...             ...     ...             ...   
239261   53             167              86       1               0   
239262   48             179              25       0               0   
239263   57             136              89       1               1   
239264   42             159              72       0               0   
239265   79             112              46       1               0   

        Hypertension  Diabetes  Obesity  Cholesterol_Level  \
0                  0         0        1                  2   
1                  1         0        0                  1   
2                  0         0        0                  1   
3                  0         1        0                  2   
4                  0         0        0                  2   
...              ...       ...      ...                ...   
239261             0         0        0                  2   
239262             0         0        1                  2   
239263             1         0        0                  2   
239264             0         0        0                  0   
239265             0         0        0                  0   

        Air_Pollution_Exposure  ...  Alcohol_Consumption  Family_History_CVD  \
0                            0  ...                    1                   0   
1                            2  ...                    0                   1   
2                            2  ...                    0                   0   
3                            2  ...                    1                   0   
4                            2  ...                    0                   0   
...                        ...  ...                  ...                 ...   
239261                       2  ...                    0                   0   
239262                       1  ...                    0                   0   
239263                       1  ...                    0                   0   
239264                       2  ...                    0                   1   
239265                       2  ...                    0                   0   

        Healthcare_Access  TCM_Use  Employment_Status  Education_Level  \
0                       0        1                  2                1   
1                       2        0                  2                2   
2                       2        0                  2                1   
3                       2        1                  0                1   
4                       1        0                  1                0   
...                   ...      ...                ...              ...   
239261                  1        1                  1                0   
239262                  2        1                  2                0   
239263                  1        1                  1                0   
239264                  2        1                  0                1   
239265                  2        0                  1                2   

        Income_Level  Chronic_Kidney_Disease  Previous_Heart_Attack  \
0                  1                       1                      0   
1                  2                       0                      0   
2                  0                       0                      0   
3                  1                       0                      1   
4                  2                       1                      0   
...              ...                     ...                    ...   
239261             1                       0                   

In [3]:
x = dt.iloc[:,0:22]
y = dt.iloc[:,22:]

In [11]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.4)

In [12]:
X_train

Age  Blood_Pressure  CVD_Risk_Score  Gender  Smoking_Status  \
63833    47              93              57       0               0   
16622    34             117              92       0               1   
163555   69             145              99       0               0   
102088   80             100              51       0               1   
122758   73             141              24       1               1   
...     ...             ...             ...     ...             ...   
176963   58             158              46       1               0   
117952   72             113              48       1               0   
173685   75             151              85       0               1   
43567    80             125              76       1               1   
199340   33             146              14       0               1   

        Hypertension  Diabetes  Obesity  Cholesterol_Level  \
63833              1         0        0                  2   
16622              0         0        1                  0   
163555             1         0        0                  1   
102088             0         0        0                  1   
122758             0         0        0                  0   
...              ...       ...      ...                ...   
176963             0         0        0                  0   
117952             0         0        0                  1   
173685             0         0        1                  1   
43567              0         0        0                  0   
199340             0         0        1                  1   

        Air_Pollution_Exposure  ...  Stress_Level  Alcohol_Consumption  \
63833                        2  ...             0                    0   
16622                        1  ...             2                    1   
163555                       2  ...             2                    0   
102088                       2  ...             1                    1   
122758                       1  ...             0                    0   
...                        ...  ...           ...                  ...   
176963                       2  ...             1                    0   
117952                       2  ...             2                    1   
173685                       1  ...             1                    0   
43567                        2  ...             1                    0   
199340                       0  ...             2                    0   

        Family_History_CVD  Healthcare_Access  TCM_Use  Employment_Status  \
63833                    0                  0        1                  1   
16622                    0                  0        0                  2   
163555                   0                  2        0                  2   
102088                   0                  1        0                  2   
122758                   0                  2        1                  1   
...                    ...                ...      ...                ...   
176963                   1                  0        0                  2   
117952                   0                  0        0                  1   
173685                   0                  2        1                  0   
43567                    0                  0        0                  1   
199340                   1                  1        0                  2   

        Education_Level  Income_Level  Chronic_Kidney_Disease  \
63833                 0             0                       0   
16622                 2             0                       0   
163555                0             1                       0   
102088                2             0                       1   
122758                3             1                       1   
...                 ...           ...                     ...   
176963                0             2                       0   
117952                2             0                       0   
173685     

In [13]:
X_test

Age  Blood_Pressure  CVD_Risk_Score  Gender  Smoking_Status  \
26050    64              94              86       1               0   
154975   55              98              29       0               1   
24366    54              94              62       0               0   
144151   86             106              45       1               0   
131563   73             142              10       1               0   
...     ...             ...             ...     ...             ...   
114259   39             151              76       1               1   
1849     41             173              13       1               1   
78194    70             137              11       0               1   
146110   55             168              24       0               1   
175570   63             158              52       1               0   

        Hypertension  Diabetes  Obesity  Cholesterol_Level  \
26050              0         0        0                  2   
154975             1         1        1                  0   
24366              1         0        0                  2   
144151             0         0        0                  1   
131563             0         0        0                  1   
...              ...       ...      ...                ...   
114259             1         0        0                  0   
1849               0         1        0                  0   
78194              1         0        0                  1   
146110             1         0        0                  0   
175570             1         0        0                  0   

        Air_Pollution_Exposure  ...  Stress_Level  Alcohol_Consumption  \
26050                        2  ...             0                    1   
154975                       2  ...             2                    1   
24366                        1  ...             0                    0   
144151                       1  ...             0                    1   
131563                       1  ...             2                    0   
...                        ...  ...           ...                  ...   
114259                       2  ...             2                    0   
1849                         1  ...             1                    0   
78194                        0  ...             0                    0   
146110                       1  ...             0                    0   
175570                       2  ...             0                    0   

        Family_History_CVD  Healthcare_Access  TCM_Use  Employment_Status  \
26050                    0                  0        0                  1   
154975                   0                  2        0                  0   
24366                    0                  2        0                  1   
144151                   0                  2        0                  2   
131563                   1                  2        1                  1   
...                    ...                ...      ...                ...   
114259                   0                  1        1                  0   
1849                     0                  1        0                  1   
78194                    0                  2        0                  2   
146110                   0                  1        0                  0   
175570                   0                  0        0                  1   

        Education_Level  Income_Level  Chronic_Kidney_Disease  \
26050                 2             1                       0   
154975                0             2                       0   
24366                 0             0                       0   
144151                2             1                       0   
131563                1             0                       0   
...                 ...           ...                     ...   
114259                3             2                       1   
1849                  1             1                       0   
78194      

In [14]:
y_train

Heart_Attack
63833              0
16622              0
163555             0
102088             0
122758             0
...              ...
176963             0
117952             1
173685             0
43567              1
199340             0

[143559 rows x 1 columns]

In [15]:
y_test

Heart_Attack
26050              0
154975             0
24366              1
144151             0
131563             0
...              ...
114259             1
1849               0
78194              0
146110             0
175570             0

[95707 rows x 1 columns]

In [16]:
sc = StandardScaler()

In [17]:
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.fit_transform(X_test)

In [18]:
X_train_std

array([[-0.72076064, -1.59699143,  0.09762766, ..., -1.21932304,
        -0.41776515, -0.33412094],
       [-1.46948407, -0.67419103,  1.44342165, ..., -1.21932304,
        -0.41776515, -0.33412094],
       [ 0.54630977,  0.40240944,  1.71258045, ...,  0.00455248,
        -0.41776515, -0.33412094],
       ...,
       [ 0.89187443,  0.63310954,  1.17426285, ..., -1.21932304,
        -0.41776515, -0.33412094],
       [ 1.17984498, -0.36659089,  0.82820154, ...,  1.228428  ,
         2.39368936, -0.33412094],
       [-1.52707818,  0.44085946, -1.55577639, ..., -1.21932304,
        -0.41776515, -0.33412094]])

In [19]:
X_test_std

array([[ 0.26584303, -1.55894154,  1.21260015, ...,  0.00378041,
        -0.41975607, -0.3327971 ],
       [-0.25360526, -1.40490399, -0.98319354, ...,  1.23026207,
        -0.41975607, -0.3327971 ],
       [-0.31132174, -1.55894154,  0.28805544, ..., -1.22270124,
        -0.41975607, -0.3327971 ],
       ...,
       [ 0.61214189,  0.09696212, -1.67660208, ..., -1.22270124,
        -0.41975607, -0.3327971 ],
       [-0.25360526,  1.29075313, -1.17580703, ...,  0.00378041,
        -0.41975607, -0.3327971 ],
       [ 0.20812656,  0.90565926, -0.09717153, ..., -1.22270124,
        -0.41975607, -0.3327971 ]])

### logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
Logi_Regression = LogisticRegression()

In [22]:
Logi_Regression.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
y_pred_logi = Logi_Regression.predict(X_test)
y_pred_logi

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
accuracy_logistic_regression_without_std = accuracy_score(y_test,y_pred_logi)
print("Prediction Accuracy By Logistic Regration without standard scaler : ",accuracy_logistic_regression_without_std)

Prediction Accuracy By Logistic Regration without standard scaler :  0.8798729455525719


In [25]:
classify_report_logi_without_std = classification_report(y_test,y_pred_logi)
print(classify_report_logi_without_std)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
Logi_Regression.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [27]:
y_pred_logi = Logi_Regression.predict(X_test_std)
y_pred_logi

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
accuracy_logistic_regression = accuracy_score(y_test,y_pred_logi)
print("Predict Accuracy by Logistic Regression with Standard Scaller : ",accuracy_logistic_regression)

Predict Accuracy by Logistic Regression with Standard Scaller :  0.8798729455525719


In [29]:
classify_report_logi = classification_report(y_test,y_pred_logi)
print(classify_report_logi)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Decision Tree Classification

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
DT_model = DecisionTreeClassifier()

In [32]:
DT_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [33]:
y_pred_DT = DT_model.predict(X_test)
y_pred_DT

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
accuracy_DT_without_std = accuracy_score(y_test,y_pred_DT)
print("Prediction Accuracy By Decision Tree Classification without standard scaler : ",accuracy_DT_without_std)

Prediction Accuracy By Decision Tree Classification without standard scaler :  0.7602787674882715


In [35]:
classify_report_DT_without_std = classification_report(y_test,y_pred_DT)
print(classify_report_DT_without_std)

              precision    recall  f1-score   support

           0       0.88      0.84      0.86     84210
           1       0.12      0.15      0.13     11497

    accuracy                           0.76     95707
   macro avg       0.50      0.50      0.50     95707
weighted avg       0.79      0.76      0.77     95707



In [36]:
DT_model.fit(X_train_std,y_train)

DecisionTreeClassifier()

In [37]:
y_pred_DT = DT_model.predict(X_test_std)
y_pred_DT

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
accuracy_DT = accuracy_score(y_test,y_pred_DT)
print("Prediction Accuracy By Decision Tree Classification with standard scaler : ",accuracy_DT)

Prediction Accuracy By Decision Tree Classification with standard scaler :  0.7615116971590374


In [39]:
classify_report_DT = classification_report(y_test,y_pred_DT)
print(classify_report_DT)

              precision    recall  f1-score   support

           0       0.88      0.84      0.86     84210
           1       0.12      0.16      0.14     11497

    accuracy                           0.76     95707
   macro avg       0.50      0.50      0.50     95707
weighted avg       0.79      0.76      0.77     95707



### Random Forest Classification

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
RF_model = RandomForestClassifier()

In [42]:
RF_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [43]:
y_pred_RF = RF_model.predict(X_test)
y_pred_RF

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
accuracy_RF_without_std = accuracy_score(y_test,y_pred_RF)
print("Prediction Accuracy By Random Forest Classification without standard scaler : ",accuracy_RF_without_std)

Prediction Accuracy By Random Forest Classification without standard scaler :  0.879852048439508


In [45]:
classify_report_RF_without_std = classification_report(y_test,y_pred_RF)
print(classify_report_RF_without_std)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



In [46]:
RF_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [47]:
y_pred_RF = RF_model.predict(X_test_std)
y_pred_RF

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
accuracy_RF = accuracy_score(y_test,y_pred_RF)
print("Prediction Accuracy By Random Forest Classification with standard scaler : ",accuracy_RF)

Prediction Accuracy By Random Forest Classification with standard scaler :  0.87986249699604


In [50]:
classify_report_RF = classification_report(y_test,y_pred_RF)
print(classify_report_RF)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



### K Nearest Neighbour Classification

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
KNN_model = KNeighborsClassifier()

In [53]:
KNN_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [54]:
y_pred_KNN = KNN_model.predict(X_test_std)
y_pred_KNN

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
accuracy_KNN = accuracy_score(y_test,y_pred_KNN)
print("Prediction Accuracy By KNearestNeighbour Classification : ",accuracy_KNN)

Prediction Accuracy By KNearestNeighbour Classification :  0.8692049693334866


In [56]:
classify_report_KNN = classification_report(y_test,y_pred_KNN)
print(classify_report_KNN)

              precision    recall  f1-score   support

           0       0.88      0.99      0.93     84210
           1       0.13      0.02      0.03     11497

    accuracy                           0.87     95707
   macro avg       0.50      0.50      0.48     95707
weighted avg       0.79      0.87      0.82     95707



### Suport Vector Classification

In [481]:
#from sklearn.svm import SVC

In [482]:
#SVC_model = SVC()

In [483]:
#SVC_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [484]:
#y_pred_svc = SVC_model.predict(X_test)
#y_pred_svc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [485]:
#accuracy_svc_without_std = accuracy_score(y_test,y_pred_svc)
#print("Prediction Accuracy By Suport Vector Classification without standard scaller : ",accuracy_svc_without_std)

Prediction Accuracy By Suport Vector Classification without standard scaller :  0.6533892382948987


In [486]:
#classify_report_svc_without_std = classification_report(y_test,y_pred_svc)
#print(classify_report_svc_without_std)

              precision    recall  f1-score   support

           0       0.65      1.00      0.79      1850
           1       1.00      0.02      0.04      1012

    accuracy                           0.65      2862
   macro avg       0.83      0.51      0.41      2862
weighted avg       0.77      0.65      0.52      2862



In [487]:
#SVC_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [488]:
#y_pred_svc = SVC_model.predict(X_test_std)
#y_pred_svc

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [489]:
#accuracy_svc = accuracy_score(y_test,y_pred_svc)
#print("Prediction Accuracy By Suport Vector Classification with standard scaler : ",accuracy_svc)

Prediction Accuracy By Suport Vector Classification with standard scaler :  0.9877707896575821


In [490]:
#classify_report_svc = classification_report(y_test,y_pred_svc)
#print(classify_report_svc)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1850
           1       1.00      0.97      0.98      1012

    accuracy                           0.99      2862
   macro avg       0.99      0.98      0.99      2862
weighted avg       0.99      0.99      0.99      2862



### Naive Bayes Classification

In [57]:
from sklearn.naive_bayes import GaussianNB

In [58]:
NB_model = GaussianNB()

In [59]:
NB_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [60]:
y_pred_nb = NB_model.predict(X_test)
y_pred_nb

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
accuracy_nb_without_std = accuracy_score(y_test,y_pred_nb)
print("Prediction Accuracy By Naive Bayes Classification without standard scaller : ",accuracy_nb_without_std)

Prediction Accuracy By Naive Bayes Classification without standard scaller :  0.8798729455525719


In [62]:
classify_report_nb_without_std = classification_report(y_test,y_pred_nb)
print(classify_report_nb_without_std)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [63]:
NB_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [64]:
y_pred_nb = NB_model.predict(X_test_std)
y_pred_nb

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [65]:
accuracy_nb = accuracy_score(y_test,y_pred_nb)
print("Prediction Accuracy By Naive Bayes Classification with standard scaler : ",accuracy_nb)

Prediction Accuracy By Naive Bayes Classification with standard scaler :  0.8798729455525719


In [66]:
classify_report_nb = classification_report(y_test,y_pred_nb)
print(classify_report_nb)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Baggin Classifier

In [67]:
#from sklearn.ensemble import BaggingClassifier , RandomForestClassifier

In [68]:
#Baggin_model = BaggingClassifier(base_estimator=RandomForestClassifier(),n_estimators=5)

In [69]:
#Baggin_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5)

In [71]:
#y_pred_bagging_rf = Baggin_model.predict(X_test)
#y_pred_bagging_rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [505]:
#accuracy_bagging_rf_without_std = accuracy_score(y_test,y_pred_bagging_rf)
#print("Prediction Accuracy By Baggin by rf Classification with standard scaler : ",accuracy_bagging_rf_without_std)

Prediction Accuracy By Baggin by rf Classification with standard scaler :  1.0


In [506]:
#classify_report_bagging_rf_without_std = classification_report(y_test,y_pred_bagging_rf)
#print(classify_report_bagging_rf_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1850
           1       1.00      1.00      1.00      1012

    accuracy                           1.00      2862
   macro avg       1.00      1.00      1.00      2862
weighted avg       1.00      1.00      1.00      2862



In [507]:
#Baggin_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5)

In [508]:
#y_pred_bagging_rf = Baggin_model.predict(X_test_std)
#y_pred_bagging_rf

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [509]:
#accuracy_bagging_rf = accuracy_score(y_test,y_pred_bagging_rf)
#print("Prediction Accuracy By Baggin by rf Classification with standard scaler : ",accuracy_bagging_rf)

Prediction Accuracy By Baggin by rf Classification with standard scaler :  0.9989517819706499


In [510]:
#classify_report_bagging_rf = classification_report(y_test,y_pred_bagging_rf)
#print(classify_report_bagging_rf)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1850
           1       1.00      1.00      1.00      1012

    accuracy                           1.00      2862
   macro avg       1.00      1.00      1.00      2862
weighted avg       1.00      1.00      1.00      2862



### AdaBoost Classification

In [72]:
from sklearn.ensemble import AdaBoostClassifier

In [73]:
Ada_model = AdaBoostClassifier(n_estimators=10,random_state=0)

In [74]:
Ada_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=10, random_state=0)

In [75]:
y_pred_Ada = Ada_model.predict(X_test)
y_pred_Ada

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
accuracy_Ada_without_std = accuracy_score(y_test,y_pred_Ada)
print("Prediction Accuracy By AdaBoost  Classification without standard scaler : ",accuracy_Ada_without_std)

Prediction Accuracy By AdaBoost  Classification without standard scaler :  0.8798729455525719


In [77]:
classify_report_Ada_without_std = classification_report(y_test,y_pred_Ada)
print(classify_report_Ada_without_std)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [78]:
Ada_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=10, random_state=0)

In [79]:
y_pred_Ada = Ada_model.predict(X_test_std)
y_pred_Ada

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [80]:
accuracy_Ada = accuracy_score(y_test,y_pred_Ada)
print("Prediction Accuracy by Adaboost Classification with Standard Scaler : ",accuracy_Ada)

Prediction Accuracy by Adaboost Classification with Standard Scaler :  0.8798729455525719


In [81]:
classify_report_Ada = classification_report(y_test,y_pred_Ada)
print(classify_report_Ada)

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707



C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Cross-Validation with KFold For classification

In [82]:
from sklearn.model_selection import KFold

In [83]:
KF_model = KFold(n_splits=3,shuffle=True,random_state=0)
model = DecisionTreeClassifier()

In [84]:
fold = 1
sc = StandardScaler()
X = np.array(x)
Y = np.array(y)
for train_index, test_index in KF_model.split(X):
    print(f"Fold {fold} accuracy without std : ")
    X_train,X_test = X[train_index] , X[test_index]
    y_train,y_test = Y[train_index] , Y[test_index]
    
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accuracy_KF_fold = accuracy_score(y_test,y_pred)
    print(accuracy_KF_fold)
    print(classification_report(y_test,y_pred))
    print('----------------------')
    fold += 1

Fold 1 accuracy without std : 
0.7613847234063895
              precision    recall  f1-score   support

           0       0.88      0.84      0.86     70184
           1       0.12      0.15      0.13      9572

    accuracy                           0.76     79756
   macro avg       0.50      0.50      0.50     79756
weighted avg       0.79      0.76      0.77     79756

----------------------
Fold 2 accuracy without std : 
0.7626982634317597
              precision    recall  f1-score   support

           0       0.88      0.85      0.86     70142
           1       0.12      0.16      0.14      9613

    accuracy                           0.76     79755
   macro avg       0.50      0.50      0.50     79755
weighted avg       0.79      0.76      0.78     79755

----------------------
Fold 3 accuracy without std : 
0.7611435019747979
              precision    recall  f1-score   support

           0       0.88      0.85      0.86     69869
           1       0.12      0.15      0.

### Accuracy Results

In [85]:
#Logistic Regression
print("Logistic Regression")
print(f"Accuracy_without_std : {accuracy_logistic_regression_without_std} , Accuracy_with_std : {accuracy_logistic_regression}")
print("\n classification_report_without_std")
print(classify_report_logi_without_std)
print("\n classification_report_with_std")
print(classify_report_logi)

print('------------------------------------------------------------------------------------------')

#Decision Tree
print('Decision Tree')
print(f"Accuracy_without_std : {accuracy_DT_without_std} , Accuracy_with_std : {accuracy_DT}")
print("\n classification_report_without_std")
print(classify_report_DT_without_std)
print("\n classification_report_with_std")
print(classify_report_DT)

print('------------------------------------------------------------------------------------------')

#Random Forest
print('Random Forest')
print(f"Accuracy_without_std : {accuracy_RF_without_std} , Accuracy_with_std : {accuracy_RF}")
print("\n classification_report_without_std")
print(classify_report_RF_without_std)
print("\n classification_report_with_std")
print(classify_report_RF)

print('------------------------------------------------------------------------------------------')

#K Nearest Neighbour
print('K Nearest Neighbour')
print(f"Accuracy_with_std : {accuracy_KNN}")
print("\n classification_report_with_std")
print(classify_report_KNN)

print('------------------------------------------------------------------------------------------')

#Support Vector Classifier
#print('Support Vector Classifier')
#print(f"Accuracy_without_std : {accuracy_svc_without_std} , Accuracy_with_std : {accuracy_svc}")
#print("\n classification_report_without_std")
#print(classify_report_svc_without_std)
#print("\n classification_report_with_std")
#print(classify_report_svc)

print('------------------------------------------------------------------------------------------')

#Naive Bayes Classification
print('Naive Bayes Classification')
print(f"Accuracy_without_std : {accuracy_nb_without_std} , Accuracy_with_std : {accuracy_nb}")
print("\n classification_report_without_std")
print(classify_report_nb_without_std)
print("\n classification_report_with_std")
print(classify_report_nb)

print('------------------------------------------------------------------------------------------')

#Bagging using RF Classification
#print('Bagging using RF Classification')
#print(f"Accuracy_without_std : {accuracy_bagging_rf_without_std} , Accuracy_with_std : {accuracy_bagging_rf}")
#print("\n classification_report_without_std")
#print(classify_report_bagging_rf_without_std)
#print("\n classification_report_with_std")
#print(classify_report_bagging_rf)

print('------------------------------------------------------------------------------------------')

#AdaBoost Classification
print('AdaBoost Classification')
print(f"Accuracy_without_std : {accuracy_Ada_without_std} , Accuracy_with_std : {accuracy_Ada}")
print("\n classification_report_without_std")
print(classify_report_Ada_without_std)
print("\n classification_report_with_std")
print(classify_report_Ada)

Logistic Regression
Accuracy_without_std : 0.8798729455525719 , Accuracy_with_std : 0.8798729455525719

 classification_report_without_std
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707


 classification_report_with_std
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     84210
           1       0.00      0.00      0.00     11497

    accuracy                           0.88     95707
   macro avg       0.44      0.50      0.47     95707
weighted avg       0.77      0.88      0.82     95707

------------------------------------------------------------------------------------------
Decision Tree
Accuracy_without_std : 0.7602787674882715 , Accuracy_with_std : 0.761